language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
script:
  - "bundle exec rake validate lint spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
matrix:
  exclude:
    # this fails on "Could not autoload package: constant Puppet::Type::Package"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
    # this fails on "can't modify frozen Symbol" in /lib/puppet/util/monkey_patches.rb
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.2.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.3.0"
notifications:
  email:
    - andretiengo@zertico.com
