name 'zertico-php5-fpm'
version '1.0.0'

author 'Andre Tiengo'
license 'Apache2'
project_page 'http://www.zertico.com'
source 'https://github.com/zertico/puppet-php5-fpm'
summary 'Puppet module for php5fpm'
description 'This module installs and manages php5 fpm. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
